### PR TITLE
Fix http2 agent doesn't work with request module

### LINKED ISSUE #174: http2 agent doesn't work with request module
Hi, 

I'm trying to use the http2 agent with the [request module](https://github.com/request/request).  Running 

    var request = require("request");
    var https = require("https");
    var myHttp1Agent = new https.Agent({ca:ca});
    request({url:"https://foo.testing/", agent:myHttp1Agent},function(error, response, body){
      console.log("request with http1 agent");
      console.log(error,body);
    });

works fine but with the http2 version

    var request = require("request");
    var http2 = require("http2");
    var myHttp2Agent = new http2.Agent({ca:ca});
    request({url:"https://foo.testing/", agent:myHttp2Agent},function(error, response, body){
      console.log("request with http2 agent");
      console.log(error,body);
    });

I get an exception:

    _http_client.js:137
        self.agent.addRequest(self, options);
                   ^

    TypeError: self.agent.addRequest is not a function
        at new ClientRequest (_http_client.js:137:16)
        at Object.exports.request (http.js:31:10)
        at Object.exports.request (https.js:181:15)
        at Request.start (/home/node/app/node_modules/request/request.js:746:30)
        at Request.end (/home/node/app/node_modules/request/request.js:1357:10)
        at end (/home/node/app/node_modules/request/request.js:574:14)
        at Immediate._onImmediate (/home/node/app/node_modules/request/request.js:588:7)
        at processImmediate [as _immediateCallback] (timers.js:383:17)

As far as I understood, http2 is supposed to be a drop in replacement for the http(s) module. So, is this a bug?

### PR DESCRIPTION
**Pull request by felicienfrancois**
Fix #174

### CODE REVIEW

**Comment by nwgh** [comment]
This looks good, but it also needs fixed in getTLS

**Comment by felicienfrancois** [comment]
I have also applied the fix to requestRaw and getRaw because even if in current implementation the agent option of `Agent.prototype.request` does not seems to be handled in plain mode (is it?), it may change in the future.

**Comment by felicienfrancois** [comment]
I just checked that test are passing. We should normally add tests for this fix but I have not the time to do it now. I may do it next week

**Comment by nwgh** [comment]
Thanks! This also continues to pass the Firefox integration tests, so it's good to go in my book.

**Pull request merged**
