### PR TITLE
Add remoteAddress and remotePort to the request handler's request.socket

### PR DESCRIPTION
**Pull request by avesus**
Node does that. It is convenient.

### CODE REVIEW

**Comment by nwgh** [comment]
Sorry for the lag in responding here - would it be possible to get some tests added for this before merging? Thanks!

**Comment by avesus** [comment]
Thanks for the reply. Unfortunately, the specs of the node-http2 claim that

**Event: 'connection' (socket, [endpoint])**: there's a second argument if the negotiation of
     HTTP/2 was successful: the reference to the [Endpoint](endpoint.html) object tied to the
     socket.

The modification contradicts to Node's specs. That 'connection' event is for 'net' module. That connection exists **before** HTTP/2 connection setup.

Could we exclude the second argument ```[endpoint]``` or move its reporting into another event / rename 'connection' event?

In my tests and production code I check in 'connection' event both ```remoteAddress``` and ```remotePort``` to implement some sort of rate limiting and poor-man sort of blacklisting **before** ever 'secureConnection' event.

The nonconformance forces me to use 'spdy' module in 2015.

Test fragment example:
``` js
    describe('https server node module specification conformance', function() {
      it('should provide API for remote client address', function(done) {
        var localAddress = null;
        var localPort = null;

        var server = http2.createServer(serverOptions, function(request, response) {
          response.end();
        }); 

        server.on('connection', function (srvSocket) {
          var remoteAddress = srvSocket.remoteAddress;
          var remotePort = srvSocket.remotePort;
          srvSocket.on('end', function () {
            expect(remoteAddress).to.equal(localAddress);
            expect(remotePort).to.equal(localPort);
            server.close();
            done();
          }); 
        })  

        server.listen(0, 'localhost', function(srvSocket) {
          var srvPort = server.address().port;
          var cltSock = net.createConnection(srvPort);
          cltSock.on('connect', function() {
            localAddress = cltSock.localAddress;
            localPort = cltSock.localPort;
            cltSock.end();
          }); 
        }); 
      }); 
    }); 
```

**Comment by nwgh** [comment]
We can discuss renaming the 'connection' event, but let's leave that for a separate issue so as to not bog this PR down (because I think this is a good PR!). I'd just like to see a quick test that makes sure request.socket.remote{Address,Port} behave as we expect in the current world before merging this.

**Comment by avesus** [comment]
Thx. Glad to collaborate!

**Pull request merged**
