### PR TITLE
Update server.js

### PR DESCRIPTION
**Pull request by yobert**
This section of code is immoral. Some poor sap is going to read this and put it into production somewhere. Please for the love of god, take this out and learn how SSL works.

### CODE REVIEW

**Comment by todesschaf** [comment]
Hi @yobert 

First of all, thanks for the PR. You're quite right that having an example that sends a server's private key isn't the kind of behavior that should be encouraged when dealing with TLS. However, there are a few issues that are causing me to not merge this.

First of all, on a technical level, this leaves the example lacking - a core feature of h2 (namely server push) is left unexplained. That's not great; we should be showing off as many cool features of h2 in our example server as we possibly can.

Second, and, in fact, more important, the attitude with which this PR was created is not the kind of behavior that should be encouraged (or even accepted) by any open source project. The borderline abusive language that you've used towards me, Gábor, and all the node-http2 contributors is, quite frankly, unacceptable. To imply that we are "immoral" or don't know "how SSL works" is contributing in bad faith, and that (much more than the technical reason above) is causing me to close this PR without merging it.

@molnarg - I have some pending work on node-http2, and I'll try to roll a more helpful example push into those changes.

**Comment by molnarg** [comment]
+1 for everything @todesschaf said. And yes, we need a better example for server push. @todesschaf: thanks for taking care of it.

**Comment by yobert** [comment]
You're absolutely right... I apologize for the snarky comment.

Maybe some more constructive feedback: What if instead of pushing the private key, we pushed something like favicon.ico that is usually auto-requested by the browser?

**Comment by todesschaf** [comment]
That would be a decent option, yes, though our example server (limited as it is) doesn't have a favicon right now :) I changed it to push the client js if you request the server js (what good is a server without a client?!), so we're not pushing private keys any more. However, if you'd like to expand the example to be more useful, that's a PR I think both @molnarg and I would accept.

**Pull request closed without merging**
